uniform vec4 vSunDir;
uniform vec4 vSkyLightDir;
uniform float fFogDensity;
uniform mat4 matWorldViewProj;
uniform mat4 matWorldView;
uniform mat4 matWorld;
uniform vec4 vCameraPos;
uniform float flora_detail;
attribute vec3 inPosition;
attribute vec3 inNormal;
attribute vec4 inColor0;
attribute vec4 inColor1;
attribute vec2 inTexCoord;
attribute vec3 inTangent;
attribute vec3 inBinormal;
varying vec4 VertexColor;
varying vec2 Tex0;
varying vec3 SunLightDir;
varying vec3 SkyLightDir;
varying vec4 PointLightDir;
varying vec4 ShadowTexCoord;
varying float Fog;
varying vec3 ViewDir;
varying vec3 WorldNormal;
void main ()
{
  vec4 tmpvar_1;
  tmpvar_1.w = 1.0;
  tmpvar_1.xyz = inPosition;
  vec4 tmpvar_2;
  vec4 tmpvar_3;
  vec4 tmpvar_4;
  vec4 tmpvar_5;
  tmpvar_5 = (matWorld * tmpvar_1);
  vec3 tmpvar_6;
  tmpvar_6 = (vCameraPos.xyz - tmpvar_5.xyz);
  float tmpvar_7;
  tmpvar_7 = (flora_detail * 0.75);
  vec4 tmpvar_8;
  tmpvar_8.w = 0.0;
  tmpvar_8.xyz = inNormal;
  vec3 tmpvar_9;
  tmpvar_9 = normalize((matWorld * tmpvar_8).xyz);
  vec4 tmpvar_10;
  tmpvar_10.w = 0.0;
  tmpvar_10.xyz = inBinormal;
  vec3 tmpvar_11;
  tmpvar_11 = normalize((matWorld * tmpvar_10).xyz);
  vec4 tmpvar_12;
  tmpvar_12.w = 0.0;
  tmpvar_12.xyz = inTangent;
  vec3 tmpvar_13;
  tmpvar_13 = normalize((matWorld * tmpvar_12).xyz);
  vec3 tmpvar_14;
  tmpvar_14 = (matWorldView * tmpvar_1).xyz;
  vec3 tmpvar_15;
  tmpvar_15.x = tmpvar_13.x;
  tmpvar_15.y = tmpvar_11.x;
  tmpvar_15.z = tmpvar_9.x;
  vec3 tmpvar_16;
  tmpvar_16.x = tmpvar_13.y;
  tmpvar_16.y = tmpvar_11.y;
  tmpvar_16.z = tmpvar_9.y;
  vec3 tmpvar_17;
  tmpvar_17.x = tmpvar_13.z;
  tmpvar_17.y = tmpvar_11.z;
  tmpvar_17.z = tmpvar_9.z;
  mat3 tmpvar_18;
  tmpvar_18[0] = tmpvar_15;
  tmpvar_18[1] = tmpvar_16;
  tmpvar_18[2] = tmpvar_17;
  tmpvar_3.xyz = ((2.0 * inColor1.xyz) - 1.0);
  tmpvar_3.w = inColor1.w;
  tmpvar_2.xyz = inColor0.zyx;
  tmpvar_2.w = (inColor0.w * clamp ((0.5 + 
    ((sqrt(dot (tmpvar_6, tmpvar_6)) - tmpvar_7) / (flora_detail - tmpvar_7))
  ), 0.0, 1.0));
  gl_Position = (matWorldViewProj * tmpvar_1);
  VertexColor = tmpvar_2;
  Tex0 = inTexCoord;
  SunLightDir = (tmpvar_18 * -(vSunDir.xyz));
  SkyLightDir = (tmpvar_18 * -(vSkyLightDir.xyz));
  PointLightDir = tmpvar_3;
  ShadowTexCoord = tmpvar_4;
  Fog = (1.0/(exp2((
    sqrt(dot (tmpvar_14, tmpvar_14))
   * fFogDensity))));
  ViewDir = normalize((vCameraPos.xyz - tmpvar_5.xyz));
  WorldNormal = tmpvar_9;
}

